### ISSUE TITLE
bugwarrior doesn't show up in search

### ISSUE THREAD

**Issue by ralphbean** [BrunoVernay/taskwarrior-site-test#6]
I'm looking at this page:

http://taskwarrior.org/tools/

And this tool doesn't show up in the search:

https://github.com/ralphbean/bugwarrior

How can I help add it?  Have I filed this bug in the right place?

**Comment by BrunoVernay** [comment]
There was a bug in my other project to update the tool list.
Should be propagated soon (few days) in the public site.

**Comment by BrunoVernay** [comment]
Solved and site updated.
Also note that the "title" field is not searched, only the description, licence and author.
But you can simply search in the page.
